# 設定ファイルに読み込ませる環境を指定
environment: "development"

environments:
  development:
    aws:
      access_key_id: "access_key_id"
      secret_access_key: "secret_access_key"
      region: "region"
      bucket_name: "backet_name"

    cdn_origin:
      domain: "xxxx.net"

  production:
    aws:
      access_key_id: "access_key_id"
      secret_access_key: "secret_access_key"
      region: "region"
      bucket_name: "bucket_name"

    cdn_origin:
      domain: "xxx.net"
data:
  resources:
    files: "./data/s3/files"

  params:
    delete_url_list: "./data/s3/params/delete_url_list.txt"
    upload_file_list: "./data/s3/params/upload_file_list.txt"

  logs:
    delete_results: "./data/s3/logs/delete_results.txt"
    upload_results: "./data/s3/logs/upload_results.txt"
