# 設定ファイルに読み込ませる環境を指定
environment: "development"

# 環境ごとの設定を記述
environments:
  development:
    aws:
      access_key_id: "YOUR_ACCESS_KEY"
      secret_access_key: "YOUR_SECRET_KEY"
      region: "your-region"
      bucket_name: "your-dev-bucket"
    # developmentではCDNを使用しないので、空にしておく。
    cdn_origin:
      domain: ""

  production:
    aws:
      access_key_id: "YOUR_ACCESS_KEY"
      secret_access_key: "YOUR_SECRET_KEY"
      region: "your-region"
      bucket_name: "your-prod-bucket"
    cdn_origin:
      domain: "your-cloudfront-domain.net"

# 入出力の設定を記述
data:
  resources:
    files: "./data/s3_operations/files"

  params:
    delete_url_list: "./data/s3_operations/params/delete_url_list.txt"
    upload_file_list: "./data/s3_operations/params/upload_file_list.txt"

  logs:
    delete_results: "./data/s3_operations/logs/delete_results.txt"
    upload_results: "./data/s3_operations/logs/upload_results.txt"
